// integrate-with-vue/src/components/PhotoEditor.vue
<template>
  <div id="editor" style="width: 100vw; height: 100vh; position: relative" />
</template>

<script>
// eslint-disable-next-line
import React from "react";
// eslint-disable-next-line
import ReactDom from "react-dom";
import { defineComponent } from "vue";
import { PhotoEditorSDKUI, UIEvent } from "photoeditorsdk";

export default defineComponent({
  name: "PhotoEditor",
  props: {},
  mounted() {
    this.initEditor();
  },
  methods: {
    async initEditor() {
      const editor = await PhotoEditorSDKUI.init({
        license: "",
        image: "./example.jpg",
        container: "#editor",
        assetBaseUrl:
          "https://cdn.img.ly/packages/imgly/photoeditorsdk/5.18.0/assets",
      });

      editor.on(UIEvent.EXPORT, (result) => {
        console.log(result);
      });
    },
  },
});
</script>

// integrate-with-next-js/components/PhotoEditor.jsx
import React, { useEffect } from 'react';
import { PhotoEditorSDKUI } from 'photoeditorsdk';

export function PhotoEditor() {
  const initEditor = async () => {
    await PhotoEditorSDKUI.init({
      container: '#editor',
      license: '',
      image: './example.jpg',
      assetBaseUrl:
        'https://cdn.img.ly/packages/imgly/photoeditorsdk/5.19.0/assets',
    });
  };

  useEffect(() => {
    initEditor();
  }, []);

  return (
    <div
      id="editor"
      style={{ position: 'relative', width: '100vw', height: '100vh' }}
    />
  );
}
